### ISSUE TITLE
Error with the workshop collection

### ISSUE THREAD

**Issue by skilinder753** [DevoTan/the-workshop#5]
![image](https://github.com/DevoTan/the-workshop/assets/169000532/f08a5c3d-b691-4ff3-816d-7b537e66dfc4)
Hello, I encounter an issue with the crafting table. When attempting to craft it, it appears as invisible and I'm unable to complete the crafting process. Additionally, the available crafting recipes with this table are not displayed.

**Comment by DevoTan** [comment]
The Workshop (CEC) does not use the metal workbench item, rather it uses the several different types of Tables from Crafting Enhanced Core.
I'm not totally sure why the Metal Workbench recipe is showing up for you; as it's turned off in the code, but this can safely be ignored.
The Crafting Enhanced Core Table's can be crafted in the Context Menu (RMB)
